import type { Metadata } from "next";
import { Roboto } from 'next/font/google';
import "./globals.css";
import './extra.css'

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['100', '300', '400', '500', '700', '900'],
  variable: '--font-roboto',
});

export const metadata: Metadata = {
  title: "EmreLutfi Restaurant Portfolio Project",
  description: "Generated by create emrelutfi",
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
      <body className={`${roboto.variable} antialiased`}>
      {children}
      </body>
      </html>
  );
}